/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package grafoOaxaca.presentacion;

import javax.swing.ImageIcon;

/**
 *
 * @author Oliver Valle
 */
public class PanelMatrizAdyacencia extends javax.swing.JPanel {

    /**
     * Creates new form PanelMatrizAdyacencia
     */
    public PanelMatrizAdyacencia() {
        initComponents();
        this.matrizAdyacencia.setIcon(new ImageIcon("src/main/java/imgs/matrizAdyacencia.jpeg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matrizAdyacencia = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1358, 672));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(matrizAdyacencia, javax.swing.GroupLayout.DEFAULT_SIZE, 1358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(matrizAdyacencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel matrizAdyacencia;
    // End of variables declaration//GEN-END:variables
}
